services:
  opensearch:
    image: ghcr.io/codelibs/fess-opensearch:2.13.0
    container_name: opensearch
    environment:
      - node.name=opensearch
      - discovery.seed_hosts=opensearch
      - cluster.initial_cluster_manager_nodes=opensearch
      - cluster.name=fess-se
      - bootstrap.memory_lock=true
      - node.roles=cluster_manager,data,ingest,ml
      - plugins.security.disabled=true
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - "OPENSEARCH_INITIAL_ADMIN_PASSWORD=qzIX0cAblpBiPuFk"
      - "FESS_DICTIONARY_PATH=/usr/share/opensearch/config/dictionary"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
    volumes:
      - sedata01:/usr/share/opensearch/data
      - sedictionary01:/usr/share/opensearch/config/dictionary
    ports:
      - 9200:9200
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    restart: unless-stopped

volumes:
  sedata01:
    driver: local
  sedictionary01:
    driver: local
